version: '3'
services:
  nginx:
    image: nginx:latest
    working_dir: /app
    expose:
      - "5000"

  nginx-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nginx 
    ports:
      - "80:80"
